site_name: Dreamfinity | Гайды
site_url: https://guides.dreamfinity.org
docs_dir: guides
site_author: <Georgii Imeshkenov aka @Veritaris, georgiiimeshkenov@gmail.com>

nav:
  - Главная страница: index.md
  - Spacecross:
      - "Гайды": Spacecross/index.md
      - "\"Материя из Matter Overdrive или генерация ресурсов\" от rrr_game": Spacecross/matter_from_MO_or_resource_generation_by_rrrgame/index.md
      - "\"Наниты и все с ними связанное\" от Sugato": Spacecross/nanites_and_everything_related_to_them_by_sugato/index.md
  - Arcanefactory:
      - "Гайды": Arcanefactory/index.md
  - Technocracy:
      - "Гайды": Technocracy/index.md
  - Mageweave:
      - "Гайды": Mageweave/index.md
      - "Hardcore Ender Expansion (HEE) от Not_a_Happy_Cat": Mageweave/hardcore_ender_expansion_by_not_a_happy_cat/index.md
  - Гайд о гайде: how_to_contribute/index.md

plugins:
  - search:
      lang:
        - ru
        - en

  - glightbox:

theme:
  name: material
  custom_dir: theme

  logo: assets/logo.svg
  favicon: assets/favicon.svg

  language: ru

  features:
    - navigation.top
    - navigation.path
#    - toc.integrate
#    - navigation.sections
#    - navigation.tabs
    - search.suggest
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: dreamfinity
      accent: dreamfinity
      toggle:
        icon: material/brightness-7
        name: Темная тема

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: dreamfinity
      accent: dreamfinity
      toggle:
        icon: material/brightness-4
        name: Светлая тема

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
